<a href="https://colab.research.google.com/github/kshipra-jadav/ztm-dl/blob/master/Introduction_To_NLP_with_TensorFlow_ZTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction To NLP - Natural Language Processing With TensorFlow 🔥

## Getting Helper Functions

In [ ]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2023-08-19 05:45:07--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2023-08-19 05:45:07 (70.9 MB/s) - ‘helper_functions.py’ saved [10246/10246]



## Getting A Text Dataset
The dataset that we are going to be using is the **Kaggle's Introduction To NLP Dataset** which is a text sample of Tweets labelled as Disaster or Not A Disaster.

Basically, Binary Classification on Tweets.

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

--2023-08-19 05:45:08--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.253.123.128, 142.250.97.128, 142.251.107.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.253.123.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.007s  

2023-08-19 05:45:08 (88.5 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [ ]:
from helper_functions import unzip_data

unzip_data("nlp_getting_started.zip")

In [ ]:
import os
for dirpath, dirname, filename in os.walk("/content"):
  print(dirpath, dirname, filename, sep=" - ")

/content - ['.config', '__pycache__', 'sample_data'] - ['sample_submission.csv', 'test.csv', 'nlp_getting_started.zip', 'train.csv', 'helper_functions.py']
/content/.config - ['logs', 'configurations'] - ['gce', '.last_opt_in_prompt.yaml', 'default_configs.db', '.last_survey_prompt.yaml', 'active_config', 'config_sentinel', '.last_update_check.json']
/content/.config/logs - ['2023.08.17'] - []
/content/.config/logs/2023.08.17 - [] - ['13.28.08.232748.log', '13.28.34.729855.log', '13.28.58.904077.log', '13.29.33.105897.log', '13.29.07.422508.log', '13.29.32.346874.log']
/content/.config/configurations - [] - ['config_default']
/content/__pycache__ - [] - ['helper_functions.cpython-310.pyc']
/content/sample_data - [] - ['anscombe.json', 'README.md', 'california_housing_train.csv', 'california_housing_test.csv', 'mnist_train_small.csv', 'mnist_test.csv']


In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

In [ ]:
train_df

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [ ]:
train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [ ]:
test_df

id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...  

[3263 rows x 4 columns]

In [ ]:
len(train_df), len(test_df)

(7613, 3263)

In [ ]:
train_df_shuffled = train_df.sample(frac=1, random_state=19)

train_df_shuffled

id             keyword                  location  \
1075   1554                bomb                       NaN   
5591   7978               razed                       NaN   
7478  10696               wreck              Victoria, BC   
5059   7210  natural%20disaster                       NaN   
3768   5351                fire       the road to success   
...     ...                 ...                       ...   
5032   7175            mudslide                       NaN   
1378   1987        bush%20fires  London/Bristol/Guildford   
757    1093           blew%20up      #SOUTHAMPTON ENGLAND   
2670   3832            detonate             Bikini bottom   
5725   8170            rescuers  ?????????????, Thailand    

                                                   text  target  
1075  New Documents Found Pointing To Japan's WWII A...       1  
5591  The Latest: More homes razed by Northern Calif...       1  
7478  @Memenaar But the design decision to 'Let's ma...       0  
5059  Expert Prepper: Financial Collapse Natural Dis...       1  
3768                     I wanna set some shit on fire.       1  
...                                                 ...     ...  
5032  You've 100% fucked up when Paul says your cake...       0  
1378  On holiday to relax sunbathe and drink ... Put...       0  
757   The universe might not actually exist scientis...       0  
2670  @mwnhappy this message will self detonate in 5...       0  
5725  VIDEO: 'We're picking up bodies from water': R...       1  

[7613 rows x 5 columns]

In [ ]:
import random

idx = random.randint(0, len(train_df) - 5)

for row in train_df[["text", "target"]][idx:idx+5].itertuples():
  _, text, target = row
  print(f"Target :- {'(real disaster)' if target == 1 else '(fake disaster)'}")
  print(f"Text :- {text}")
  print("---\n")


Target :- (fake disaster)
Text :- -- small bag from the bottom the wounded hero shakes it. A Senzu Bean falls from it. Gohan‰Ûªs surprised. Shakes the pouch once more but --
---

Target :- (real disaster)
Text :- @wocowae Officer Wounded Suspect Killed in Exchange of Gunfire http://t.co/QI2BDvkab7 ushed
---

Target :- (real disaster)
Text :- Police Officer Wounded Suspect Dead After Exchanging Shots: Richmond police officer wounded suspect killed a... http://t.co/w0r8EAOKA0
---

Target :- (real disaster)
Text :- Gunshot wound #9 is in the bicep. The only one of the ten wounds that is not in the chest/torso area.  #KerrickTrial #JonathanFerrell
---

Target :- (fake disaster)
Text :- @CharlesDagnall He's getting 50 here I think. Salt. Wounds. Rub. In.
---



## Making A Validation Dataset

In [ ]:
from sklearn.model_selection import train_test_split

X = train_df_shuffled["text"]
y = train_df_shuffled["target"]

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=19)

len(X_train), len(X_valid), len(y_train), len(y_valid)

(6090, 1523, 6090, 1523)

In [ ]:
X_train.head(), y_train.head()

(1780    MotoGP Indianapolis: Espargaro: Layout 'worrie...
 5492    Reddit Will Now Quarantine OffensiveåÊContent ...
 747        @DamnAarielle yo timeline blew up so damn fast
 2255    Tarp is protecting outfield and cannot be move...
 6329    Virgin galactic crash: early unlocking of brak...
 Name: text, dtype: object,
 1780    0
 5492    0
 747     0
 2255    1
 6329    1
 Name: target, dtype: int64)

## Converting Text to Numbers

When we're dealing with NLP problems, we often need to convert the text that we have to numbers.

This will help the neural network to understand the text that we're feeding it since the neural network doesn't understand text at all. It only understand numbers.

Hence, to convert text to numbers, we can use one of the two techniques below:-
1. **Tokenization** - direct mapping of a token `a token can be a word or a character` to a number.
2. **Embedding** - creating a matrix of feature vector for each token

### Text Vectorization (Tokenization)

In [ ]:
X_train.head()

1780    MotoGP Indianapolis: Espargaro: Layout 'worrie...
5492    Reddit Will Now Quarantine OffensiveåÊContent ...
747        @DamnAarielle yo timeline blew up so damn fast
2255    Tarp is protecting outfield and cannot be move...
6329    Virgin galactic crash: early unlocking of brak...
Name: text, dtype: object

In [ ]:
from tensorflow.keras.layers import TextVectorization

# Using the default TextVectorization Parameters

text_vectorizer = TextVectorization(max_tokens=None, # how many words you want to keep in vocabulary? None means the method will decide automatically and any word outside the vocabulary will be marked as <OOV>
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None, # do you want to create groups of n-words?
                                    output_mode="int", # mapping tokens to numbers
                                    output_sequence_length=None, # how long do you want the sequences to be?
                                    pad_to_max_tokens=False)

In [ ]:
# Finding the average number of words in each tweet in the training dataset

round(sum([len(i.split()) for i in X_train]) / len(X_train))

15

In [ ]:
# Hence, by average, each tweet is 15 words long.
# Setting up the hyperparameters now

max_vocab_length = 10000 # Only include 10000 words in our vocabulary. All the other words will be marked <OOV>
max_words = round(sum([len(i.split()) for i in X_train]) / len(X_train))

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_words)
text_vectorizer

In [ ]:
# Fit the text vectorizer to the training data

text_vectorizer.adapt(X_train)

In [ ]:
# Create a sample sentence and tokenize it

sample = "There's a flood in my street!"
text_vectorizer([sample])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[295,   3, 210,   4,  13, 746,   0,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [ ]:
# Choosing a random sentence from training data and tokenizing it
import random

random_sentence = random.choice(X_train)
vec_sentence = text_vectorizer([random_sentence])

print(f"Original Text - \n{random_sentence} {len(random_sentence.split())}")
print(f"\n\n Vectorized Version - \n {vec_sentence.numpy()}")

Original Text - 
Stuck in a rainstorm? Stay toward the middle of the road. Most streets are crowned so water tends to pool on the sides. 23


 Vectorized Version - 
 [[2486    4    3  607  473 2457    2 1178    6    2  388  212 1612   23
     1]]


In [ ]:
# Getting the unique words in Vocabulary

(text_vectorizer.get_vocabulary()[:5],
text_vectorizer.get_vocabulary()[-5:])

(['', '[UNK]', 'the', 'a', 'in'],
 ['mirrors', 'mirrorlady2', 'mirmanda11', 'mirkwood', 'mirad'])

### Creating an Embedding using an Embedding Layer

In [ ]:
from tensorflow.keras.layers import Embedding

embedding = Embedding(input_dim=max_vocab_length,
                      output_dim=128,
                      input_length=max_words)
embedding

In [ ]:
import random

random_sentence = random.choice(X_train)
print(f"Original Sentence :-\n{random_sentence}\n\n")

vecs = text_vectorizer([random_sentence])
embeds = embedding(vecs)

print(f"Embedding :- \n{embeds}")

Original Sentence :-
500 deaths a year from foodborne illness... @frackfreelancs dears... @DECCgovuk @frackfree_eu @tarleton_sophie http://t.co/JSccX8k0jA


Embedding :- 
[[[-0.03543208 -0.03985905  0.04293051 ... -0.04991112 -0.00064403
    0.00874919]
  [-0.00108174  0.01135432 -0.03999795 ...  0.02637355 -0.04006324
    0.02584574]
  [-0.00401099 -0.03876498 -0.0033671  ...  0.02519857  0.03053198
    0.00024941]
  ...
  [ 0.00042063 -0.00166676 -0.0334394  ...  0.04415182 -0.00685954
    0.01768328]
  [ 0.00193634  0.03205106  0.02974382 ... -0.00488124 -0.0018986
   -0.00895923]
  [ 0.00193634  0.03205106  0.02974382 ... -0.00488124 -0.0018986
   -0.00895923]]]


## Modelling A Text Dataset and Running A Series of Experiments

1. Naive Bayes with TF-IDF encoder (baseline)
2. Feed-forward neural network (dense model)
2. LSTM (RNN)
2. GRU (RNN)
2. Bidirectional-LSTM (RNN)
2. 1D Convolutional Neural Network
2. TensorFlow Hub Pretrained Feature Extractor
2. TensorFlow Hub Pretrained Feature Extractor (10% of data)

### Model 0: Naive Bayes (baseline model)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

model_0 = Pipeline([
  ('tfidf', TfidfVectorizer()),
  ('clf', MultinomialNB())
])

model_0.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
baseline_score = model_0.score(X_valid, y_valid)
baseline_score

0.7944845699277742

In [ ]:
baseline_preds = model_0.predict(X_valid)
baseline_preds[:20]

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_true=y_valid, y_pred=baseline_preds))

              precision    recall  f1-score   support

           0       0.76      0.93      0.84       864
           1       0.87      0.62      0.72       659

    accuracy                           0.79      1523
   macro avg       0.82      0.77      0.78      1523
weighted avg       0.81      0.79      0.79      1523



### Model 1: A Simple Dense Model

In [ ]:
# Making a simple Dense model using Keras Functional API
from tensorflow.keras.layers import Input, Dense, GlobalAveragePooling1D
from tensorflow.keras import Model

inputs = Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = embedding(x)
x = GlobalAveragePooling1D()(x) # to condense feature vector for each sentence
outputs = Dense(1, activation="sigmoid")(x)

model_1 = Model(inputs, outputs, name="model_1_dense")

In [ ]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_3 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d (G  (None, 128)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense_1 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
N

In [ ]:
model_1.compile(optimizer="adam",
                loss="binary_crossentropy",
                metrics=["accuracy"])

model_1.fit(X_valid, y_valid, epochs=5, validation_data=(X_valid, y_valid))

Epoch 1/5
48/48 [==============================] - 7s 128ms/step - loss: 0.6301 - accuracy: 0.8096 - val_loss: 0.5832 - val_accuracy: 0.7971
Epoch 2/5
48/48 [==============================] - 3s 60ms/step - loss: 0.5508 - accuracy: 0.7997 - val_loss: 0.5094 - val_accuracy: 0.8306
Epoch 3/5
48/48 [==============================] - 1s 31ms/step - loss: 0.4821 - accuracy: 0.8418 - val_loss: 0.4439 - val_accuracy: 0.8641
Epoch 4/5
48/48 [==============================] - 1s 28ms/step - loss: 0.4208 - accuracy: 0.8641 - val_loss: 0.3866 - val_accuracy: 0.8936
Epoch 5/5
48/48 [==============================] - 1s 15ms/step - loss: 0.3681 - accuracy: 0.8995 - val_loss: 0.3380 - val_accuracy: 0.9094


In [ ]:
model1_pred_probs = model_1.predict(X_valid)

48/48 [==============================] - 0s 2ms/step


In [ ]:
model1_pred_probs[0], model1_pred_probs.shape

(array([0.84848404], dtype=float32), (1523, 1))

In [ ]:
import tensorflow as tf

model1_preds = tf.round(tf.squeeze(model1_pred_probs)).numpy()

model1_preds[:20]

array([1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0.], dtype=float32)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_true=y_valid, y_pred=model1_preds))

              precision    recall  f1-score   support

           0       0.87      0.98      0.93       864
           1       0.98      0.81      0.89       659

    accuracy                           0.91      1523
   macro avg       0.92      0.90      0.91      1523
weighted avg       0.92      0.91      0.91      1523



## Visualizing Learned Embeddings

In [ ]:
# Getting the words in vocabulary from the text vectorization layer
vocabulary = text_vectorizer.get_vocabulary()

len(vocabulary), vocabulary[:10]

(10000, ['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'])

In [ ]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_3 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d (G  (None, 128)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense_1 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
N

In [87]:
# Getting the weight matrix of the embedding layer
# these are the numerical representations of each token in our training data that the embedding layer has learnt for ~5 epochs

embed_weights = model_1.get_layer("embedding").get_weights()[0]
embed_weights, embed_weights.shape

# Each token (10000 tokens) is expanded to 128 size long token array

(array([[ 0.05215545,  0.04555801,  0.05142589, ...,  0.02487354,
         -0.0543836 ,  0.01249286],
        [ 0.01229   ,  0.03197525, -0.03047548, ...,  0.0258945 ,
         -0.02319461,  0.02151782],
        [ 0.04546978, -0.02859472,  0.02159206, ..., -0.02857375,
          0.03152478, -0.02694254],
        ...,
        [-0.01133684, -0.04440205,  0.00181194, ...,  0.02302266,
          0.02114178, -0.04003222],
        [-0.00193857,  0.02463246, -0.03017612, ..., -0.02389888,
          0.00501438,  0.00072428],
        [-0.03557234,  0.04380206, -0.0350129 , ...,  0.02323841,
          0.04880286, -0.04483381]], dtype=float32),
 (10000, 128))

In [93]:
# Saving the vectors and metadata to disk so that we can visualize them in projector.tensorflow.org
import io

vectors = io.open("vectors.tsv", "w", encoding="utf-8")
metadata = io.open("metadata.tsv", "w", encoding="utf-8")

for index, word in enumerate(vocabulary):
  if index == 0:
    continue
  vec = embed_weights[index]
  vectors.write("\t".join([str(x) for x in vec]) + "\n")
  metadata.write(word + "\n")

vectors.close()
metadata.close()

In [94]:
try:
  from google.colab import files
  files.download('vectors.tsv')
  files.download('metadata.tsv')
except Exception:
  pass

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>